version: '3.5'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4666:4566"
    environment:
      - SERVICES=iam,s3,apigateway,lambda,dynamodb,cloudformation
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=testUser
      - AWS_SECRET_ACCESS_KEY=testAccessKey
