version: '3'

networks:
  network:
    name: docker-network

services:
  db:
    networks:
      - network
    ports:
      - 3306:3306
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-udbuser',
          '-pdbpassword',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
  lending-platform:
    networks:
      - network
    container_name: lending-platform
    depends_on:
      db:
        condition: service_healthy
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      HTTP_PORT: 8080
      DB_URL: mysql://dbuser:dbpassword@db:3306/lending_platform
    ports:
      - 8080:8080
      - 9229:9229
    command: >
      sh -c '\
        npm run dev
      '