version: '3'

networks:
  network:
    name: docker-network

services:
  db:
    networks:
      - network
    container_name: db
    image: postgres
    ports:
      - 5432:5432
    volumes:
        - ./cart-service/db/init.sql:/docker-entrypoint-initdb.d/init-cart.sql
        - ./product-service/db/init.sql:/docker-entrypoint-initdb.d/init-product.sql
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword

  cart-service:
    networks:
      - network
    container_name: cart-service
    depends_on:
      - db
    volumes: 
      - ./cart-service:/usr/src/app
      - /usr/src/app/node_modules
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    environment:
      APP_PORT: 3000
      DATABASE_CONNECTION_STRING: postgres://dbuser:dbpassword@db:5432/cart
    ports:
      - 3000:3000
      - 9229:9229
    command: >
      sh -c '\
        npm run dev
      '

  product-service:
    networks:
      - network
    container_name: product-service
    depends_on:
      - db
    volumes: 
      - ./product-service:/usr/src/app
      - /usr/src/app/node_modules
    build:
      context: ./product-service
      dockerfile: Dockerfile
    environment:
      APP_PORT: 3001
      DATABASE_CONNECTION_STRING: postgres://dbuser:dbpassword@db:5432/product
    ports:
      - 3001:3000
      - 9230:9229
    command: >
      sh -c '\
        npm run dev
      '
